apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: my-service-b-tcp
  name: my-service-b-tcp
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 5672
    - name: "3002"
      port: 3002
      targetPort: 15672
  selector:
    io.kompose.service: my_service_b
  type: LoadBalancer
status:
  loadBalancer: {}
