apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: my-service-a-tcp
  name: my-service-a-tcp
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 5672
    - name: "3003"
      port: 3003
      targetPort: 15672
  selector:
    io.kompose.service: my_service_a
  type: LoadBalancer
status:
  loadBalancer: {}
