apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  containers:
    - image: ertugrulbal/rabbitmq
      name: my-message-queue
      ports:
        - containerPort: 5672
        - containerPort: 15672
      resources: {}
  restartPolicy: OnFailure
status: {}
